name: "Update Assets"

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  update:
    name: Update assets

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node 16
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Compile Asset
        run: |
          npm ci
          npm run prod

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Assets (ci)
